/*Generated By Hukiry-lua Do not Edit*/
using Server;

namespace Game.Http
{
    /// <summary>
    /// ---所有活动：定时请求，领取操作
    /// </summary>
    public class msg_1201 : IProto
	{
		/// <summary>
		/// 0=接收成功，1=请求数据，2=活动完成，3=活动进度值
		/// </summary>
		public byte state = 0;
		/// <summary>
		/// 功能类型 SystemFunctionType
		/// </summary>
		public byte type = 0;
		/// <summary>
		/// 角色id
		/// </summary>
		public int roleId = 0;
		/// <summary>
		/// 活动ID
		/// </summary>
		public short configId = 0;
		/// <summary>
		/// 活动ID
		/// </summary>
		public bool isFinshed = false;
		/// <summary>
		/// 活动开始时间
		/// </summary>
		public uint creatTime = 0;
		/// <summary>
		/// 活动结束时间
		/// </summary>
		public uint expirateTime = 0;
		/// <summary>
		/// 活动进度字符串
		/// </summary>
		public string strValue = string.Empty;
		/// <summary>
		/// 活动id和参数值:后端传值使用
		/// </summary>
		public string paramsValue = string.Empty;

		public void Write(ByteBlock block)
		{
			block.Write(this.state);
			block.Write(this.type);
			block.Write(this.roleId);
			block.Write(this.configId);
			block.Write(this.isFinshed);
			block.Write(this.creatTime);
			block.Write(this.expirateTime);
			block.Write(this.strValue);
			block.Write(this.paramsValue);
		}

		public void Read(ByteBlock block)
		{
			this.state = (byte)block.ReadByte();
			this.type = (byte)block.ReadByte();
			this.roleId = block.ReadInt32();
			this.configId = block.ReadInt16();
			this.isFinshed = block.ReadBoolean();
			this.creatTime = block.ReadUInt32();
			this.expirateTime = block.ReadUInt32();
			this.strValue = block.ReadString();
			this.paramsValue = block.ReadString();
		}
	}

}
