/*Generated By Hukiry-lua Do not Edit*/
using Server;

namespace Game.Http
{
    /// <summary>
    /// ---排行榜
    /// </summary>
    public class msg_1301 : IProto
	{
		/// <summary>
		/// 功能类型 1=周排行，2=月排行，3=年排行
		/// </summary>
		public byte type = 0;
		/// <summary>
		/// json数据：角色id，角色昵称，角色等级，角色任务积分
		/// </summary>
		public string jsonDatas = string.Empty;

		public void Write(ByteBlock block)
		{
			block.Write(this.type);
			block.Write(this.jsonDatas);
		}

		public void Read(ByteBlock block)
		{
			this.type = (byte)block.ReadByte();
			this.jsonDatas = block.ReadString();
		}
	}

	/// <summary>
	/// ---反馈数据：存入到数据库，3个工作日内回复
	/// </summary>
	public class msg_1302 : IProto
	{
		/// <summary>
		/// 角色id
		/// </summary>
		public int roleId = 0;
		/// <summary>
		/// 反馈问题类型：1=游戏问题，2=崩溃问题，3=充值问题，4=其他问题
		/// </summary>
		public byte type = 0;
		/// <summary>
		/// 反馈描述：30个字
		/// </summary>
		public string content = string.Empty;
		/// <summary>
		/// 电子邮件
		/// </summary>
		public string e_mail = string.Empty;

		public void Write(ByteBlock block)
		{
			block.Write(this.roleId);
			block.Write(this.type);
			block.Write(this.content);
			block.Write(this.e_mail);
		}

		public void Read(ByteBlock block)
		{
			this.roleId = block.ReadInt32();
			this.type = (byte)block.ReadByte();
			this.content = block.ReadString();
			this.e_mail = block.ReadString();
		}
	}

}
