/*Generated By Hukiry-lua Do not Edit*/
using Server;

namespace Game.Http
{
    /// <summary>
    /// ---服务器错误处理
    /// </summary>
    public class msg_1901 : IProto
	{
		/// <summary>
		/// 请求的cmd
		/// </summary>
		public ushort cmd = 0;
		/// <summary>
		/// 错误码
		/// </summary>
		public byte code = 0;

		public void Write(ByteBlock block)
		{
			block.Write(this.cmd);
			block.Write(this.code);
		}

		public void Read(ByteBlock block)
		{
			this.cmd = block.ReadUInt16();
			this.code = (byte)block.ReadByte();
		}
	}

}
