/*Generated By Hukiry-lua Do not Edit*/
using Server;
using System.Collections.Generic;

namespace Game.Http
{
    /// <summary>
    /// ---好友消息
    /// </summary>
    public class GFriendInfo : IProto
	{
		/// <summary>
		/// 用户id
		/// </summary>
		public uint roleId = 0;
		/// <summary>
		/// 0=帮助一点生命，1=申请好友，2=被申请好友，3=邀请，4=被邀请挑战，5=删除好友，6，取消申请，7，取消挑战
		/// </summary>
		public byte state = 0;
		/// <summary>
		/// 等级
		/// </summary>
		public ushort level = 0;
		/// <summary>
		/// 昵称
		/// </summary>
		public string nick = string.Empty;
		/// <summary>
		/// 头像
		/// </summary>
		public byte headId = 0;
		/// <summary>
		/// 好友邀请地图
		/// </summary>
		public byte mapId = 0;

		public void Write(ByteBlock block)
		{
			block.Write(this.roleId);
			block.Write(this.state);
			block.Write(this.level);
			block.Write(this.nick);
			block.Write(this.headId);
			block.Write(this.mapId);
		}

		public void Read(ByteBlock block)
		{
			this.roleId = block.ReadUInt32();
			this.state = (byte)block.ReadByte();
			this.level = block.ReadUInt16();
			this.nick = block.ReadString();
			this.headId = (byte)block.ReadByte();
			this.mapId = (byte)block.ReadByte();
		}
	}

	/// <summary>
	/// ---社团成员信息
	/// </summary>
	public class GMemeberInfo : IProto
	{
		/// <summary>
		/// 用户id
		/// </summary>
		public uint roleId = 0;
		/// <summary>
		/// 等级
		/// </summary>
		public ushort level = 0;
		/// <summary>
		/// 昵称
		/// </summary>
		public string nick = string.Empty;
		/// <summary>
		/// 头像
		/// </summary>
		public byte headId = 0;
		/// <summary>
		/// 是团主
		/// </summary>
		public bool isMasser = false;

		public void Write(ByteBlock block)
		{
			block.Write(this.roleId);
			block.Write(this.level);
			block.Write(this.nick);
			block.Write(this.headId);
			block.Write(this.isMasser);
		}

		public void Read(ByteBlock block)
		{
			this.roleId = block.ReadUInt32();
			this.level = block.ReadUInt16();
			this.nick = block.ReadString();
			this.headId = (byte)block.ReadByte();
			this.isMasser = block.ReadBoolean();
		}
	}

	/// <summary>
	/// ---生命信息
	/// </summary>
	public class GLifeInfo : IProto
	{
		/// <summary>
		/// 聊天角色id
		/// </summary>
		public uint Id = 0;
		/// <summary>
		/// 寻求帮助时间
		/// </summary>
		public uint time = 0;
		/// <summary>
		/// 状态：请求帮助，帮助其他
		/// </summary>
		public byte state = 0;
		/// <summary>
		/// 昵称
		/// </summary>
		public string nick = string.Empty;
		/// <summary>
		/// 帮助进度
		/// </summary>
		public byte count = 0;

		public void Write(ByteBlock block)
		{
			block.Write(this.Id);
			block.Write(this.time);
			block.Write(this.state);
			block.Write(this.nick);
			block.Write(this.count);
		}

		public void Read(ByteBlock block)
		{
			this.Id = block.ReadUInt32();
			this.time = block.ReadUInt32();
			this.state = (byte)block.ReadByte();
			this.nick = block.ReadString();
			this.count = (byte)block.ReadByte();
		}
	}

	/// <summary>
	/// ---聊天消息
	/// </summary>
	public class GChatInfo : IProto
	{
		/// <summary>
		/// 聊天角色id
		/// </summary>
		public uint Id = 0;
		/// <summary>
		/// 聊天时间
		/// </summary>
		public uint time = 0;
		/// <summary>
		/// 聊天内容
		/// </summary>
		public string content = string.Empty;

		public void Write(ByteBlock block)
		{
			block.Write(this.Id);
			block.Write(this.time);
			block.Write(this.content);
		}

		public void Read(ByteBlock block)
		{
			this.Id = block.ReadUInt32();
			this.time = block.ReadUInt32();
			this.content = block.ReadString();
		}
	}

	/// <summary>
	/// ---好友系统30个
	/// </summary>
	public class msg_1501 : IProto
	{
		/// <summary>
		/// 玩家id
		/// </summary>
		public uint roleId = 0;
		/// <summary>
		/// 1=请求消息列表，2=我的好友，3=陌生人列表
		/// </summary>
		public byte state = 0;
		/// <summary>
		/// 好友的id操作
		/// </summary>
		public uint friendId = 0;
		/// <summary>
		/// 好友消息
		/// </summary>
		public List<GFriendInfo> friendInfos = new List<GFriendInfo>();

		public void Write(ByteBlock block)
		{
			block.Write(this.roleId);
			block.Write(this.state);
			block.Write(this.friendId);
			block.WriteClassList(this.friendInfos);
		}

		public void Read(ByteBlock block)
		{
			this.roleId = block.ReadUInt32();
			this.state = (byte)block.ReadByte();
			this.friendId = block.ReadUInt32();
			block.ReadClassList(this.friendInfos);
		}
	}

	/// <summary>
	/// ---好友消息
	/// </summary>
	public class msg_1502 : IProto
	{
		/// <summary>
		/// 玩家id
		/// </summary>
		public uint roleId = 0;
		/// <summary>
		/// 操作类型
		/// </summary>
		public byte type = 0;
		/// <summary>
		/// 操作好友状态
		/// </summary>
		public byte state = 0;
		/// <summary>
		/// 好友的id操作
		/// </summary>
		public uint friendId = 0;
		/// <summary>
		/// 好友邀请地图
		/// </summary>
		public byte mapId = 0;

		public void Write(ByteBlock block)
		{
			block.Write(this.roleId);
			block.Write(this.type);
			block.Write(this.state);
			block.Write(this.friendId);
			block.Write(this.mapId);
		}

		public void Read(ByteBlock block)
		{
			this.roleId = block.ReadUInt32();
			this.type = (byte)block.ReadByte();
			this.state = (byte)block.ReadByte();
			this.friendId = block.ReadUInt32();
			this.mapId = (byte)block.ReadByte();
		}
	}

	/// <summary>
	/// ---留言板
	/// </summary>
	public class msg_1503 : IProto
	{
		/// <summary>
		/// 玩家id
		/// </summary>
		public uint roleId = 0;
		/// <summary>
		/// 好友的id操作
		/// </summary>
		public uint friendId = 0;
		/// <summary>
		/// 状态：获取聊天记录，发送聊天
		/// </summary>
		public byte state = 0;
		/// <summary>
		/// 发送聊天的消息 限制30个字符
		/// </summary>
		public string message = string.Empty;
		/// <summary>
		/// 聊天记录 限制20条
		/// </summary>
		public List<GChatInfo> chatInfos = new List<GChatInfo>();

		public void Write(ByteBlock block)
		{
			block.Write(this.roleId);
			block.Write(this.friendId);
			block.Write(this.state);
			block.Write(this.message);
			block.WriteClassList(this.chatInfos);
		}

		public void Read(ByteBlock block)
		{
			this.roleId = block.ReadUInt32();
			this.friendId = block.ReadUInt32();
			this.state = (byte)block.ReadByte();
			this.message = block.ReadString();
			block.ReadClassList(this.chatInfos);
		}
	}

	/// <summary>
	/// ---社团队友：限制30人
	/// </summary>
	public class msg_1504 : IProto
	{
		/// <summary>
		/// 玩家id
		/// </summary>
		public uint roleId = 0;
		/// <summary>
		/// 帮助好友id
		/// </summary>
		public uint friendId = 0;
		/// <summary>
		/// 社团id
		/// </summary>
		public uint gassId = 0;
		/// <summary>
		/// 社团状态
		/// </summary>
		public byte state = 0;
		/// <summary>
		/// 社团队友
		/// </summary>
		public List<GMemeberInfo> memeberInfos = new List<GMemeberInfo>();
		/// <summary>
		/// 社团生命列表
		/// </summary>
		public List<GLifeInfo> lifeInfos = new List<GLifeInfo>();

		public void Write(ByteBlock block)
		{
			block.Write(this.roleId);
			block.Write(this.friendId);
			block.Write(this.gassId);
			block.Write(this.state);
			block.WriteClassList(this.memeberInfos);
			block.WriteClassList(this.lifeInfos);
		}

		public void Read(ByteBlock block)
		{
			this.roleId = block.ReadUInt32();
			this.friendId = block.ReadUInt32();
			this.gassId = block.ReadUInt32();
			this.state = (byte)block.ReadByte();
			block.ReadClassList(this.memeberInfos);
			block.ReadClassList(this.lifeInfos);
		}
	}

}
