/*Generated By Hukiry-lua Do not Edit*/
using Server;
using System.Collections.Generic;
namespace Game.Http
{
    /// <summary>
    /// ---请求登录
    /// </summary>
    public class msg_1001 : IProto
	{
		/// <summary>
		/// 首次登录的设备id
		/// </summary>
		public string deviceId = string.Empty;
		/// <summary>
		/// 首次登录的语言
		/// </summary>
		public string lang = string.Empty;
		/// <summary>
		/// 登录方式
		/// </summary>
		public byte login_type = 0;
		/// <summary>
		/// 登录平台
		/// </summary>
		public byte platform = 0;
		/// <summary>
		/// 签名时间
		/// </summary>
		public uint signTime = 0;
		/// <summary>
		/// 签名字符串
		/// </summary>
		public string sign = string.Empty;

		public void Write(ByteBlock block)
		{
			block.Write(this.deviceId);
			block.Write(this.lang);
			block.Write(this.login_type);
			block.Write(this.platform);
			block.Write(this.signTime);
			block.Write(this.sign);
		}

		public void Read(ByteBlock block)
		{
			this.deviceId = block.ReadString();
			this.lang = block.ReadString();
			this.login_type = (byte)block.ReadByte();
			this.platform = (byte)block.ReadByte();
			this.signTime = block.ReadUInt32();
			this.sign = block.ReadString();
		}
	}

	/// <summary>
	/// ---货币资源
	/// </summary>
	public class itemsResource : IProto
	{
		/// <summary>
		/// 货币类型
		/// </summary>
		public byte type = 0;
		/// <summary>
		/// 货币数量
		/// </summary>
		public int number = 0;

		public void Write(ByteBlock block)
		{
			block.Write(this.type);
			block.Write(this.number);
		}

		public void Read(ByteBlock block)
		{
			this.type = (byte)block.ReadByte();
			this.number = block.ReadInt32();
		}
	}

	/// <summary>
	/// ---货币资源
	/// </summary>
	public class itemsMeta : IProto
	{
		/// <summary>
		/// 货币类型
		/// </summary>
		public byte numberId = 0;
		/// <summary>
		/// 货币数量
		/// </summary>
		public byte state = 0;

		public void Write(ByteBlock block)
		{
			block.Write(this.numberId);
			block.Write(this.state);
		}

		public void Read(ByteBlock block)
		{
			this.numberId = (byte)block.ReadByte();
			this.state = (byte)block.ReadByte();
		}
	}

	/// <summary>
	/// ---上传游戏数据
	/// </summary>
	public class msg_1002 : IProto
	{
		/// <summary>
		/// 角色ID
		/// </summary>
		public uint roleId = 0;
		/// <summary>
		/// 昵称
		/// </summary>
		public string roleNick = string.Empty;
		/// <summary>
		/// 当前的生命时间
		/// </summary>
		public uint curLifeTime = 0;
		/// <summary>
		/// 是绑定登录
		/// </summary>
		public string token = string.Empty;
		/// <summary>
		/// 上传数据的时间戳
		/// </summary>
		public uint timeStamp = 0;
		/// <summary>
		/// 用于切换设备
		/// </summary>
		public byte state = 0;
		/// <summary>
		/// 语言代码
		/// </summary>
		public string lanCode = string.Empty;
		/// <summary>
		/// 货币数据集合
		/// </summary>
		public List<itemsResource> items = new List<itemsResource>();
		/// <summary>
		/// 货币数据集合
		/// </summary>
		public short headID = 0;
		/// <summary>
		/// 绑定的设备id
		/// </summary>
		public string deviceId = string.Empty;
		/// <summary>
		/// 加入的社团id
		/// </summary>
		public uint gassId = 0;
		/// <summary>
		/// 元宇宙的id集合
		/// </summary>
		public List<itemsMeta> metaMapIds = new List<itemsMeta>();

		public void Write(ByteBlock block)
		{
			block.Write(this.roleId);
			block.Write(this.roleNick);
			block.Write(this.curLifeTime);
			block.Write(this.token);
			block.Write(this.timeStamp);
			block.Write(this.state);
			block.Write(this.lanCode);
			block.WriteClassList(this.items);
			block.Write(this.headID);
			block.Write(this.deviceId);
			block.Write(this.gassId);
			block.WriteClassList(this.metaMapIds);
		}

		public void Read(ByteBlock block)
		{
			this.roleId = block.ReadUInt32();
			this.roleNick = block.ReadString();
			this.curLifeTime = block.ReadUInt32();
			this.token = block.ReadString();
			this.timeStamp = block.ReadUInt32();
			this.state = (byte)block.ReadByte();
			this.lanCode = block.ReadString();
			block.ReadClassList(this.items);
			this.headID = block.ReadInt16();
			this.deviceId = block.ReadString();
			this.gassId = block.ReadUInt32();
			block.ReadClassList(this.metaMapIds);
		}
	}

	/// <summary>
	/// ---注销或绑定
	/// </summary>
	public class msg_1003 : IProto
	{
		/// <summary>
		/// 0=接收成功，1=注销，2=绑定, 3=切换设备, 4=修改昵称
		/// </summary>
		public byte state = 0;
		/// <summary>
		/// 角色登录
		/// </summary>
		public uint roleId = 0;
		/// <summary>
		/// 上传绑定Token
		/// </summary>
		public string token = string.Empty;
		/// <summary>
		/// 绑定的设备id
		/// </summary>
		public string deviceId = string.Empty;
		/// <summary>
		/// 昵称
		/// </summary>
		public string roleNick = string.Empty;
		/// <summary>
		/// 绑定的账号类型
		/// </summary>
		public byte bindAccount = 0;

		public void Write(ByteBlock block)
		{
			block.Write(this.state);
			block.Write(this.roleId);
			block.Write(this.token);
			block.Write(this.deviceId);
			block.Write(this.roleNick);
			block.Write(this.bindAccount);
		}

		public void Read(ByteBlock block)
		{
			this.state = (byte)block.ReadByte();
			this.roleId = block.ReadUInt32();
			this.token = block.ReadString();
			this.deviceId = block.ReadString();
			this.roleNick = block.ReadString();
			this.bindAccount = (byte)block.ReadByte();
		}
	}

	/// <summary>
	/// ---心跳时间
	/// </summary>
	public class msg_1004 : IProto
	{
		/// <summary>
		/// 时间戳
		/// </summary>
		public uint timeStamp = 0;

		public void Write(ByteBlock block)
		{
			block.Write(this.timeStamp);
		}

		public void Read(ByteBlock block)
		{
			this.timeStamp = block.ReadUInt32();
		}
	}

	/// <summary>
	/// ---时间戳
	/// </summary>
	public class msg_1005 : IProto
	{
		/// <summary>
		/// 
		/// </summary>
		public uint roleId = 0;
		/// <summary>
		/// 货币类型
		/// </summary>
		public byte type = 0;
		/// <summary>
		/// 货币数量
		/// </summary>
		public byte number = 0;

		public void Write(ByteBlock block)
		{
			block.Write(this.roleId);
			block.Write(this.type);
			block.Write(this.number);
		}

		public void Read(ByteBlock block)
		{
			this.roleId = block.ReadUInt32();
			this.type = (byte)block.ReadByte();
			this.number = (byte)block.ReadByte();
		}
	}

	/// <summary>
	/// ---货币数量
	/// </summary>
	public class msg_1006 : IProto
	{
		/// <summary>
		/// 
		/// </summary>
		public uint roleId = 0;
		/// <summary>
		/// 修改头像id
		/// </summary>
		public short headID = 0;

		public void Write(ByteBlock block)
		{
			block.Write(this.roleId);
			block.Write(this.headID);
		}

		public void Read(ByteBlock block)
		{
			this.roleId = block.ReadUInt32();
			this.headID = block.ReadInt16();
		}
	}

}
