/*Generated By Hukiry-lua Do not Edit*/
using Server;
using System.Collections.Generic;
namespace Game.Http
{
    /// <summary>
    /// 
    /// </summary>
    public class mailData : IProto
	{
		/// <summary>
		/// 邮件和公告id
		/// </summary>
		public short id = 0;
		/// <summary>
		/// 邮件和公告标题，角色昵称
		/// </summary>
		public string title = string.Empty;
		/// <summary>
		/// 邮件和公告内容
		/// </summary>
		public bool isLife = false;
		/// <summary>
		/// 邮件和公告内容
		/// </summary>
		public string content = string.Empty;
		/// <summary>
		/// 邮件和公告奖励：后面用于充值补发json数据
		/// </summary>
		public string rewards = string.Empty;

		public void Write(ByteBlock block)
		{
			block.Write(this.id);
			block.Write(this.title);
			block.Write(this.isLife);
			block.Write(this.content);
			block.Write(this.rewards);
		}

		public void Read(ByteBlock block)
		{
			this.id = block.ReadInt16();
			this.title = block.ReadString();
			this.isLife = block.ReadBoolean();
			this.content = block.ReadString();
			this.rewards = block.ReadString();
		}
	}

	/// <summary>
	/// ------邮件和公告数据操作
	/// </summary>
	public class msg_1101 : IProto
	{
		/// <summary>
		/// 0=接收成功，1=请求数据，2=读取，3=删除，4=领取
		/// </summary>
		public byte state = 0;
		/// <summary>
		/// 功能类型
		/// </summary>
		public byte type = 0;
		/// <summary>
		/// 角色id
		/// </summary>
		public int roleId = 0;
		/// <summary>
		/// 邮件和公告id 用于已读
		/// </summary>
		public short id = 0;
		/// <summary>
		/// 公告语言代码
		/// </summary>
		public string lanCode = string.Empty;
		/// <summary>
		/// 邮件和公告id
		/// </summary>
		public List<mailData> mails = new List<mailData>();

		public void Write(ByteBlock block)
		{
			block.Write(this.state);
			block.Write(this.type);
			block.Write(this.roleId);
			block.Write(this.id);
			block.Write(this.lanCode);
			block.WriteClassList(this.mails);
		}

		public void Read(ByteBlock block)
		{
			this.state = (byte)block.ReadByte();
			this.type = (byte)block.ReadByte();
			this.roleId = block.ReadInt32();
			this.id = block.ReadInt16();
			this.lanCode = block.ReadString();
			block.ReadClassList(this.mails);
		}
	}

}
