/*Generated By Hukiry-lua Do not Edit*/
using Server;
using System.Collections.Generic;
namespace Game.Http
{
    /// <summary>
    /// ---元宇宙信息：发起或点赞
    /// </summary>
    public class MetaInfo : IProto
	{
		/// <summary>
		/// 发起者的id
		/// </summary>
		public int friendId = 0;
		/// <summary>
		/// 地图的点赞数量
		/// </summary>
		public int likeNum = 0;
		/// <summary>
		/// 发起者地图id
		/// </summary>
		public byte numberId = 0;
		/// <summary>
		/// 挑战状态，0=未接受挑战，1=接受过挑战
		/// </summary>
		public byte state = 0;
		/// <summary>
		/// 地图的所有评论
		/// </summary>
		public string comment = string.Empty;

		public void Write(ByteBlock block)
		{
			block.Write(this.friendId);
			block.Write(this.likeNum);
			block.Write(this.numberId);
			block.Write(this.state);
			block.Write(this.comment);
		}

		public void Read(ByteBlock block)
		{
			this.friendId = block.ReadInt32();
			this.likeNum = block.ReadInt32();
			this.numberId = (byte)block.ReadByte();
			this.state = (byte)block.ReadByte();
			this.comment = block.ReadString();
		}
	}

	/// <summary>
	/// ---元宇宙数据:元宇宙表，发给谁，数据就存入给对方
	/// </summary>
	public class msg_1601 : IProto
	{
		/// <summary>
		/// 0=对战消息，1=发起挑战，2=点赞，3=评论
		/// </summary>
		public byte state = 0;
		/// <summary>
		/// 我的角色id
		/// </summary>
		public int roleId = 0;
		/// <summary>
		/// 好友角色id
		/// </summary>
		public int friendId = 0;
		/// <summary>
		/// 好友点赞的地图id
		/// </summary>
		public byte numberId = 0;
		/// <summary>
		/// 好友发起评论
		/// </summary>
		public string comment = string.Empty;
		/// <summary>
		/// 地图返回的挑战消息
		/// </summary>
		public List<MetaInfo> metaInfos = new List<MetaInfo>();

		public void Write(ByteBlock block)
		{
			block.Write(this.state);
			block.Write(this.roleId);
			block.Write(this.friendId);
			block.Write(this.numberId);
			block.Write(this.comment);
			block.WriteClassList(this.metaInfos);
		}

		public void Read(ByteBlock block)
		{
			this.state = (byte)block.ReadByte();
			this.roleId = block.ReadInt32();
			this.friendId = block.ReadInt32();
			this.numberId = (byte)block.ReadByte();
			this.comment = block.ReadString();
			block.ReadClassList(this.metaInfos);
		}
	}

}
