/*Generated By Hukiry-c# Do not Edit*/
using System;
namespace Hukiry.Protobuf {
	public sealed class protocal {
		/// <summary>
		///---所有活动：定时请求，领取操作
		/// <summary>
		public const int msg_1201 = 1201;
		/// <summary>
		///---排行榜
		/// <summary>
		public const int msg_1301 = 1301;
		/// <summary>
		///---反馈数据：存入到数据库，3个工作日内回复
		/// <summary>
		public const int msg_1302 = 1302;
		/// <summary>
		///---服务器错误处理
		/// <summary>
		public const int msg_1901 = 1901;
		/// <summary>
		///---好友系统30个
		/// <summary>
		public const int msg_1501 = 1501;
		/// <summary>
		///---好友消息
		/// <summary>
		public const int msg_1502 = 1502;
		/// <summary>
		///---留言板
		/// <summary>
		public const int msg_1503 = 1503;
		/// <summary>
		///---社团队友：限制30人
		/// <summary>
		public const int msg_1504 = 1504;
		/// <summary>
		///---请求登录
		/// <summary>
		public const int msg_1001 = 1001;
		/// <summary>
		///---上传游戏数据
		/// <summary>
		public const int msg_1002 = 1002;
		/// <summary>
		///---注销或绑定
		/// <summary>
		public const int msg_1003 = 1003;
		/// <summary>
		///---心跳时间
		/// <summary>
		public const int msg_1004 = 1004;
		/// <summary>
		///---时间戳
		/// <summary>
		public const int msg_1005 = 1005;
		/// <summary>
		///---货币数量
		/// <summary>
		public const int msg_1006 = 1006;
		/// <summary>
		///------邮件和公告数据操作
		/// <summary>
		public const int msg_1101 = 1101;
		/// <summary>
		///---元宇宙数据:元宇宙表，发给谁，数据就存入给对方
		/// <summary>
		public const int msg_1601 = 1601;
		/// <summary>
		///---商店数据
		/// <summary>
		public const int msg_1401 = 1401;
		/// <summary>
		/// 获取协议号
		/// <summary>
		public (int dot, int tip) GetProtoCode(int pbCode) {
			return (pbCode / 100, pbCode % 100);
		}
	}
}
