/*Generated By Hukiry-lua Do not Edit*/
using Server;

namespace Game.Http
{
    /// <summary>
    /// ---商店数据
    /// </summary>
    public class msg_1401 : IProto
	{
		/// <summary>
		/// 0=接收成功，1=请求商店数据，2=支付
		/// </summary>
		public byte state = 0;
		/// <summary>
		/// 角色id
		/// </summary>
		public int roleId = 0;
		/// <summary>
		/// 商店id
		/// </summary>
		public int shopId = 0;
		/// <summary>
		/// 商店id
		/// </summary>
		public short price = 0;

		public void Write(ByteBlock block)
		{
			block.Write(this.state);
			block.Write(this.roleId);
			block.Write(this.shopId);
			block.Write(this.price);
		}

		public void Read(ByteBlock block)
		{
			this.state = (byte)block.ReadByte();
			this.roleId = block.ReadInt32();
			this.shopId = block.ReadInt32();
			this.price = block.ReadInt16();
		}
	}

}
