//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 轻压Install.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("轻压Install.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] HukiryMenuExtension {
            get {
                object obj = ResourceManager.GetObject("HukiryMenuExtension", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] HukiryPropertySheet {
            get {
                object obj = ResourceManager.GetObject("HukiryPropertySheet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] HukiryThumbnailExtendion {
            get {
                object obj = ResourceManager.GetObject("HukiryThumbnailExtendion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 ServerRegistrationManager.exe install HukiryThumbnailExtendion.dll -codebase
        ///ServerRegistrationManager.exe install HukiryMenuExtension.dll -codebase
        ///ServerRegistrationManager.exe install HukiryPropertySheet.dll -codebase 的本地化字符串。
        /// </summary>
        internal static string installThumbnail {
            get {
                return ResourceManager.GetString("installThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] ServerRegistrationManager {
            get {
                object obj = ResourceManager.GetObject("ServerRegistrationManager", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] SharpShell {
            get {
                object obj = ResourceManager.GetObject("SharpShell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon sip {
            get {
                object obj = ResourceManager.GetObject("sip", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 ServerRegistrationManager.exe uninstall HukiryThumbnailExtendion.dll
        ///ServerRegistrationManager.exe uninstall HukiryMenuExtension.dll
        ///ServerRegistrationManager.exe uninstall HukiryPropertySheet.dll 的本地化字符串。
        /// </summary>
        internal static string uninstallThumbnail {
            get {
                return ResourceManager.GetString("uninstallThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CLASSES_ROOT\*\shell\Hukiry]
        ///@=&quot;用轻压打开&quot;
        ///&quot;Icon&quot;=&quot;##&quot;
        ///
        ///[HKEY_CLASSES_ROOT\*\shell\Hukiry\Command]
        ///@=&quot;## \&quot;%1\&quot;&quot;
        ///
        ///[HKEY_CLASSES_ROOT\.hxp]
        ///@=&quot;File.hxp&quot;
        ///&quot;Content Type&quot;=&quot;File/hxp&quot;
        ///
        ///[HKEY_CLASSES_ROOT\.hxp\ShellNew]
        ///&quot;NullFile&quot;=&quot;&quot;
        ///
        ///[HKEY_CLASSES_ROOT\.sip]
        ///@=&quot;File.hxp&quot;
        ///&quot;Content Type&quot;=&quot;File/sip&quot;
        ///
        ///[HKEY_CLASSES_ROOT\.sip\ShellNew]
        ///&quot;NullFile&quot;=&quot;&quot;
        ///
        ///[HKEY_CLASSES_ROOT\File.hxp]
        ///@=&quot;轻压文件&quot;
        ///
        ///[HKEY_CLASSES_ROOT\File.hxp\DefaultIcon]
        ///@=&quot;##&quot;
        ///
        ///[HKEY_CLASSES [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 轻压 {
            get {
                return ResourceManager.GetString("轻压", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 轻压app {
            get {
                object obj = ResourceManager.GetObject("轻压app", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
